name: firebase_image_upload
description: "A new Flutter project."


publish_to: 'none' 



version: 1.0.0+1

environment:
  sdk: ^3.9.0



dependencies:
  flutter:
    sdk: flutter

  #theme
  cupertino_icons: ^1.0.8
  
  #service
  flutter_dotenv: ^6.0.0
 
  #functionality
  image_picker: ^1.2.0

  #state management
  flutter_mobx: ^2.0.6
  mobx: ^2.5.0

  #network
  dio: ^5.9.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.7.0
  flutter_lints: ^6.0.0
  mobx_codegen: ^2.3.0



flutter:

  uses-material-design: true

  
  assets:
   - .env
  
  
  
